#include "constants.h"

const int BORDEROFFSET = 10;
const int GRIDWIDTH = 200;
const int GRIDHEIGHT = 200;
const int SQUARESIZE = 20;
const int NUMBEROFCELLS = ((GRIDWIDTH*GRIDHEIGHT)/SQUARESIZE)/SQUARESIZE;
const int NUMBEROFMINES = NUMBEROFCELLS/SQUARESIZE*1.5;
